name: Build APK - Attendance Bunker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-attendance-bunker-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Attendance Bunker repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10 for Attendance Bunker
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Android Build Tools
        run: |
          sdkmanager "build-tools;34.0.0"


      - name: Install Buildozer and dependencies for Attendance Bunker
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK for Attendance Bunker
        run: |
          buildozer android debug

      - name: Upload Attendance Bunker APK
        uses: actions/upload-artifact@v4
        with:
          name: attendance-bunker-apk
          path: bin/*.apk
