name: Build APK - Attendance Bunker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-attendance-bunker-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Attendance Bunker repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Buildozer & dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools git
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK with Buildozer
        run: |
          buildozer android debug --verbose

      - name: Upload Attendance Bunker APK
        uses: actions/upload-artifact@v4
        with:
          name: attendance-bunker-apk
          path: bin/*.apk
